export { default as AboutMe } from './AboutMe/AboutMe'
export { default as Contact } from './Contact/Contact'
export { default as Footer } from './Footer/Footer'
export { default as Header } from './Header/Header'
export { default as Portfolio } from './Portfolio/Portfolio'
export { default as Resume } from './Resume/Resume'