export { default as BackgroundAnimation } from './BackgroundAnimation/BackgroundAnimation'
export { default as Project } from './Project/Project'
export { default as Navigation } from './Navigation/Navigation'
export { default as ContactForm } from './ContactForm/ContactForm'
export { default as ContactInfo } from './ContactInfo/ContactInfo'